### ISSUE TITLE
schema.datacite.org/meta/ redirects to kernel-4.0 instead of the latest (kernel-4.3)

### ISSUE THREAD

**Issue by DavidFichtmueller** [datacite/schema#79]
When a user is viewing an old version of the Schema, e.g. https://schema.datacite.org/meta/kernel-4.2/ and then removes the specific version, so that https://schema.datacite.org/meta/ is remaining and hits enter, the user is then redirected to https://schema.datacite.org/meta/kernel-4.0/ , where as a reasonable expectation would be to get redirected to the latest version: https://schema.datacite.org/meta/kernel-4.3/ (currently)

I assume this redirect is caused by this line in the config: 

https://github.com/datacite/schema/blob/490c19863cf712582c646d2d402cb32da30ec6b0/config.rb#L6
which wasn't updated for the releases after 4.0. The redirect should be fixed and mechanisms should be put in place to make sure this doesn't happen again (e.g. point in release checklist or a more complex redirect that looks for the latest version)

**Comment by mfenner** [comment]
@DavidFichtmueller thanks for raising this issue. The fix I have implemented is to redirect to `meta/kernel-4/index.html`, as this is the latest version of the metadata schema. Starting with schema 3.0 we switched to using the major schema version in DataCite XML, so http://datacite.org/schema/kernel-4 instead of http://datacite.org/schema/kernel-4.3.
